### PR TITLE
When available, use the mouse event buttons property.

### LINKED ISSUE #781: On Firefox, mosemove events always indicate the left mouse button is clicked
For example, binding to `geo.event.feature.mouseclick` will always fire events where the property `evt.mouse.buttonsDown.left` is `true`.

The cause appears to be that GeoJS [uses `MouseEvent.which`](https://github.com/OpenGeoscience/geojs/blob/2854ccb087d30aa87fed2984929a29e0a0027940/src/mapInteractor.js#L854) to determine which mouse buttons are pressed. According to [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/which) and [a bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1048294), `MouseEvent.which` does not work properly on Firefox.

[`MouseEvent.buttons`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons) should probably be used instead, though it appears to not be supported by Safari.

### PR DESCRIPTION
**Pull request by manthey**
Firefox erroneously sets the which value to the left button even when it is not held down.  The `buttons` property is correct for browsers that support it, but Safari doesn't, so we have to fall back to using the `which` value in that case.

This fixes #781.

### CODE REVIEW

File: src/mapInteractor.js [hunk 1]
```diff
@@ -850,18 +850,27 @@ var mapInteractor = function (args) {
...
-          if (evt.which) {
-            m_mouse.buttons[evt.which] = true;
-          }
-          break;
       }
     }
+    /* When handling touch events, evt.which can be a string, in which case
+     * handle a "button" with that name -- a non-integer string will not
+     * evaluate as being between 1 and 3. */
+    if (evt.which && !(evt.which >= 1 && evt.which <= 3)) {
```
Comment (brianhelba) [inline src/mapInteractor.js]: Should this be a separate conditional block, whereby one of the other previous conditionals runs with this too?

Comment (manthey) [reply src/mapInteractor.js]: It doesn't need to be, as in the touch events where it will get triggered, it can never also be in a `mouseup` event, and we want it to trigger regardless of the buttons conditional.
